version: '3'

services:
  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - $PWD/locustfile.py:/home/locust/locustfile.py
    command: -f /home/locust/locustfile.py --master -H http://master:8089  --autostart --expect-workers 2

  worker:
    image: locustio/locust
    volumes:
      - $PWD/locustfile.py:/home/locust/locustfile.py
    command: -f /home/locust/locustfile.py  --worker --master-host master